[project]
name = "GoCueCellAnalysis"
authors = [{name = "Roger Herikstad", email = "rherikstad@proton.me"},
		  ]
version = "0.1.0"
dependencies = ["juliacall",
				"matplotlib",
				"numpy",
				"scipy"
				]
readme = "README.md"
